hibernate:
  format_sql: true;
  
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  application:
    name: KentArsivi
  datasource:
    password: DbPassword
    username: DbUsername
    url: jdbc:mysql://localhost:3306/DbName
    


    
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true
        search:
          default:
           # Specify the Lucene Directory For Full Text Search 
            directory_provider: filesystem
            indexBase: indexpath
    show-sql: true

    
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 300MB
      max-request-size: 315MB
      
    
archive:
  root-folder-path: /Users/mustafaalp/Desktop/Masaüstü/KentArsiviRootFolder

    